### ISSUE TITLE
ResourcePlacementThr

### ISSUE THREAD

**Issue by Bobbbe** [MIAgimir/Ox_Inventory-ItemsTemplate#3]
hello :) thx for your jobs, it's very cool. 
i have this issu for props streams.```
[   5364766] [b2699_GTAProce] ResourcePlacementThr/ Physics validation failed for asset bzzz_foodpack_donut001.ydr.
[   5364766] [b2699_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
[   5364766] [b2699_GTAProce] ResourcePlacementThr/ Details: Poly 0 edge reference is invalid. It leads to vertex 65369, when there are only 169 vertices.
[   5379969] [b2699_GTAProce] ResourcePlacementThr/ Physics validation failed for asset bzzz_foodpack_donut002.ydr.
[   5379969] [b2699_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
[   5379969] [b2699_GTAProce] ResourcePlacementThr/ Details: Poly 0 edge reference is invalid. It leads to vertex 65369, when there are only 169 vertices.
[   5394657] [b2699_GTAProce] ResourcePlacementThr/ Physics validation failed for asset bzzz_cigarpack_cig002.ydr.
[   5394657] [b2699_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
[   5394657] [b2699_GTAProce] ResourcePlacementThr/ Details: Poly 8 edge reference is invalid. It leads to vertex 65519, when there are only 120 vertices.```
i dont test other but maybe it's same. maybe you can update with  zmodeler3 .ybn and .ydr

**Comment by MIAgimir** [comment]
Good eye for the issue, unfortunately I did not create the models. The credit goes to Mrs. Bzzz for the creation and (I would assume) support for the models. 

Here is their Cfx page if you would like to reach out to them.
-https://forum.cfx.re/u/bzzzi/summary
