### ISSUE TITLE
Error loading ox_inventory

### ISSUE THREAD

**Issue by HazeWorksOnFiveMServer** [MIAgimir/Ox_Inventory-ItemsTemplate#4]
[    c-scripting-core] Creating script environments for ox_inventory
[ script:ox_inventory] Error loading script modules/init.lua in resource ox_inventory: @ox_inventory/modules/items/server.lua:428: attempt to call a nil value (global 'setContainerProperties')
[ script:ox_inventory] stack traceback:
[ script:ox_inventory] 	@ox_inventory/modules/items/server.lua:428: in local 'chunk'
[ script:ox_inventory] 	@ox_lib/require/server.lua:51: in function 'require'
[ script:ox_inventory] 	@ox_inventory/server.lua:12: in local 'chunk'
[ script:ox_inventory] 	@ox_lib/require/server.lua:51: in function 'require'
[ script:ox_inventory] 	(...tail calls...)
[    c-scripting-core] Failed to load script modules/init.lua.
[           resources] Started resource ox_inventory

**Comment by MIAgimir** [comment]
I need to know more, like are there errors in the scripts where you placed the chunks of code or were they placed correctly? If you want you can attach the files here and I can look at them, but I need more than just this.

**Comment by HazeWorksOnFiveMServer** [comment]
[before - server.txt](https://github.com/MIAgimir/Ox_Inventory-ItemsTemplate/files/11314531/before.-.server.txt)
[after - server.txt](https://github.com/MIAgimir/Ox_Inventory-ItemsTemplate/files/11314532/after.-.server.txt)

**Comment by MIAgimir** [comment]
What version are you using for ox_inventory? 

This issue is coming from the **setContainerProperties** on 428. In the version I have, that chunk from 428 to 449 would go in the containers.lua, not server.lua

[after.-.server_fix.txt](https://github.com/MIAgimir/Ox_Inventory-ItemsTemplate/files/11323541/after.-.server_fix.txt)

**Comment by HazeWorksOnFiveMServer** [comment]
ox_inventory 2.27.1

**Comment by MIAgimir** [comment]
Try that file in my previous post and see if that works

**Comment by HazeWorksOnFiveMServer** [comment]
Done it so far no error in the console
